name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ganti jadi 'master' kalau branch kamu namanya master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd halo-sehat
            git fetch --all
            git reset --hard origin/main
          
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PORT=3306" >> .env
          
            sudo docker build -t halosehat-app .
            sudo docker rm -f halosehat-container || true
            sudo docker run -d -p 80:3000 --env-file .env halosehat-app
